package com.jackson_siro.visongbook.models;

public class PostsSearch {
    public Integer postid;
    public String categoryid;
    public String type;
    public String basetype;
    public String hidden;
    public String queued;
    public String acount;
    public String selchildid;
    public String closedbyid;
    public String upthumbs;
    public String downthumbs;
    public String netthumbs;
    public String views;
    public String hotness;
    public String flagcount;
    public String title;
    public String tags;
    public String created;
    public String name;
    public String categoryname;
    public String categorybackpath;
    public String categoryids;
    public String userthumb;
    public String userflag;
    public String userfavoriteq;
    public String userid;
    public String cookieid;
    public String createip;
    public String points;
    public String flags;
    public String level;
    public String email;
    public String handle;
    public String avatarblobid;
    public String avatarwidth;
    public String avatarheight;
    public String order;
}
